apiVersion: v1
kind: Service
metadata:
  name: redis-notifire
  namespace: notifire
spec:
  selector:
    app: notifire
    component: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379